version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: periferia_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: periferia_backend
    build: ./backend
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    container_name: periferia_front
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
